# Generated by Django 4.0 on 2022-03-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branchregister',
            fields=[
                ('branchid', models.AutoField(primary_key=True, serialize=False)),
                ('branchname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobno', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='default.png', upload_to='images')),
                ('businessname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companys')),
            ],
        ),
    ]
