# Generated by Django 4.0 on 2022-03-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchregister',
            name='cmpnyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.companys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchregister',
            name='businessname',
            field=models.CharField(max_length=255),
        ),
    ]
