# Generated by Django 4.0 on 2022-03-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_branchregister_cmpnyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchregister',
            name='businessname',
        ),
        migrations.RemoveField(
            model_name='branchregister',
            name='cmpnyid',
        ),
    ]
