# Generated by Django 4.0 on 2022-03-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app1', '0003_remove_branchregister_businessname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchregister',
            name='cmpnyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.companys'),
            preserve_default=False,
        ),
    ]
