# Generated by Django 4.0 on 2022-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_branchregister_cmpnyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchregister',
            name='businessname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
