# Generated by Django 4.0 on 2022-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_branchregister_businessname'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchregister',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
