# Generated by Django 4.0 on 2022-03-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_branchregister_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('branchname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='images')),
                ('branchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.branchregister')),
            ],
        ),
    ]
